### ISSUE TITLE
Can you connect this to a telegram bot

### ISSUE THREAD

**Issue by Christian-RIZE** [kayabaNerve/tip-bot#16]
See title?

**Comment by kayabaNerve** [comment]
Theoretically, yes, if you rewrite the main file. The rest is abstracted enough. That said, it'd require hours of work and I don't actively maintain this or monitor it.

**Comment by 98farhan94** [comment]
@kayabaNerve I am aware you don't maintain it, but does the code still work for Discord?

**Comment by kayabaNerve** [comment]
It should. I've heard comments about the giveaway command having problem with its emojis. Discord also recently revamped how bots interact with the API, so the URL used in its discord.js likely needs to be updated. Finally, Ethereum fees have been rampant recently, so that needs tuning/automation.
