### ISSUE TITLE
Exceeds block gas

### ISSUE THREAD

**Issue by rabTAI** [kayabaNerve/tip-bot#3]
node main.js 
(node:97725) UnhandledPromiseRejectionWarning: Error: Returned error: exceeds block gas limit

I get this error and I changed the different value in
` await contract.methods.approve(master, "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff").send({
        from: address,
        gas: 4712388,
        gasPrice: 14000000000`
but no luck

**Comment by kayabaNerve** [comment]
The only gas we specify is 70k. You seem to have changed it to almost 5 million.

If 70k wasn't enough, set it to 150k.
