### ISSUE TITLE
New erc20 Token

### ISSUE THREAD

**Issue by rabTAI** [kayabaNerve/tip-bot#4]
So I am using this for a new ERC20 token.

Every time I type !deposit, it creates a new address, but if users already have an address, it should not create a new address, right?

Also, the transaction of the coin inside the same wallet should be fee-less. I don't want to pay gas for every time I do a transaction. Only withdraw should charge the gas, not the tip within the discord tips.

**Comment by kayabaNerve** [comment]
Each user gets a single address. If it's creating multiple addresses for the same user, it's a problem with the database.

Tips are feeless. Only withdrawals charge a fee.

**Comment by rabTAI** [comment]
I will check database. In database user is created but does not have any address on it. Every !deposit creates a new address in geth but does not update to database.

**Comment by kayabaNerve** [comment]
Closing as this is user error.
