### ISSUE TITLE
have problem executing this code

### ISSUE THREAD

**Issue by rabTAI** [kayabaNerve/tip-bot#5]
`//Unlock the master account and send the new slave Ether.
    await web3.eth.personal.unlockAccount(master);
    await web3.eth.sendTransaction({
        from: master,
        to: address,
        value: web3.utils.toWei("0.001")
    });`
Is it a write way to do it >>        value: web3.utils.toWei("0.001")

what about using like this >>  value: web3.toWei(5, "ether"), gas:100000});

or >> web3.utils.toWei('990', 'ether')

**Comment by kayabaNerve** [comment]
The address should only need 0.001 ETH. Why do you want to send it 5, or 990, ETH?

This is majorly out of scope for the tip bot.
