### ISSUE TITLE
Error while using !giveaway 

### ISSUE THREAD

**Issue by stfN2128** [kayabaNerve/tip-bot#9]
Hi! 
i get the following error when i try to start a giveaway: 

Bot prints: "undefined undefined COIN GIVEAWAY! undefined undefined 1 minute, 0 seconds are left. 2 winners. 0.5 COINS each. undefined"

While the server prints the following in the background: 
(node:19632) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString'                                               of undefined
    at Timeout.setTimeout [as _onTimeout] (/root/tip-bot/commands/giveaway.js:13:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:19632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error ori                                              ginated either by throwing inside of an async function without a catch block, or by reject                                              ing a promise which was not handled with .catch(). (rejection id: 1)
(node:19632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In                                               the future, promise rejections that are not handled will terminate the Node.js process wi                                              th a non-zero exit code.
(node:19632) UnhandledPromiseRejectionWarning: TypeError: Emoji must be a string or Emoji/                                              ReactionEmoji
    at Message.react (/root/tip-bot/node_modules/discord.js/src/structures/Message.js:452:                                              23)
    at Object.module.exports [as giveaway] (/root/tip-bot/commands/giveaway.js:184:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error ori                                              ginated either by throwing inside of an async function without a catch block, or by reject                                              ing a promise which was not handled with .catch(). (rejection id: 2)

Any idea? 

Thanks man!

**Comment by kayabaNerve** [comment]
Discord changed how they handle emojis. Because of that, the Discord Bot cannot successfully send giveaway messages involving the confetti emoji.
